- name: Configure firewall for Ubuntu and CentOS
  hosts: ubuntu:centos
  become: yes
  tasks:
    - name: Ubuntu tasks
      block:
        - name: Install ufw (Uncomplicated Firewall) on Ubuntu
          ansible.builtin.apt:
            name: ufw
            state: present
          
        - name: Enable SSH port (allow incoming SSH connections) on Ubuntu
          ansible.builtin.command:
            cmd: ufw allow ssh

        # Add more Ubuntu-specific tasks here

        - name: Enable firewall on Ubuntu
          ansible.builtin.command:
            cmd: ufw --force enable
      when: ansible_os_family == 'Debian'

    - name: CentOS tasks
      block:
        - name: Install firewalld on CentOS
          ansible.builtin.yum:
            name: firewalld
            state: present
          
        - name: Start firewalld service on CentOS
          ansible.builtin.service:
            name: firewalld
            state: started
            enabled: yes

        - name: Enable SSH port (allow incoming SSH connections) on CentOS
          ansible.builtin.command:
            cmd: firewall-cmd --permanent --add-service=ssh

        # Add more CentOS-specific tasks here

        - name: Reload firewall on CentOS
          ansible.builtin.command:
            cmd: firewall-cmd --reload
      when: ansible_os_family == 'RedHat'
