---

- hosts: all
  become: true
  pre_tasks:

  - name: Configure dpkg (Ubuntu)
    shell: |
      dpkg --configure -a
    when: ansible_distribution == "Ubuntu"

  - name: Install Updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install LAMP Stack (Ubuntu)
    tags: lamp,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: "MariaDB- Restarting/Enabling"
    service:
      name: mariadb
      state: restarted
      enabled: true

- hosts: nagios_ubuntu
  become: true
  roles:
    - nagios_ubuntu

- hosts: prometheus_ubuntu
  become: true
  roles:
    - prometheus_ubuntu

- hosts: elk_ubuntu
  become: true
  roles:
    - elk_ubuntu
